In [6]:
import numpy as np

w = np.arange(8).reshape((4, 2))
w.shape

(4, 2)

In [7]:
w

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
b = np.arange(2)
b

array([0, 1])

In [9]:
w + b

array([[0, 2],
       [2, 4],
       [4, 6],
       [6, 8]])

In [20]:
a = np.arange(4).reshape(4, 1)
a

array([[0],
       [1],
       [2],
       [3]])

In [22]:
wa = np.multiply(w, a)
wa

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21]])

In [23]:
wa.sum(axis=0)

array([28, 34])

In [26]:
al = wa.sum(axis=0) + b
al

array([28, 35])

In [25]:
al

array([28, 35])

In [34]:
relu = np.maximum(0, al)
relu

array([28, 35])