In [6]:
import numpy as np

w = np.arange(8).reshape((4, 2))
w.shape

(4, 2)

In [7]:
w

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
b = np.arange(2)
b

array([0, 1])

In [9]:
w + b

array([[0, 2],
       [2, 4],
       [4, 6],
       [6, 8]])

In [20]:
a = np.arange(4).reshape(4, 1)
a

array([[0],
       [1],
       [2],
       [3]])

In [22]:
wa = np.multiply(w, a)
wa

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21]])

In [23]:
wa.sum(axis=0)

array([28, 34])

In [26]:
al = wa.sum(axis=0) + b
al

array([28, 35])

In [25]:
al

array([28, 35])

In [34]:
relu = np.maximum(0, al)
relu

array([28, 35])

In [11]:
import torch
x = torch.tensor(3.0, requires_grad=True)
y = 3 * x ** 2
y

tensor(27., grad_fn=<MulBackward0>)

In [10]:
y.backward()
x.grad

tensor(18.)

In [3]:
x.data

tensor(3.)

In [17]:
y.grad_fn

In [12]:
z = 4 * y **3
z

tensor(78732., grad_fn=<MulBackward0>)

In [13]:
z.backward()

In [14]:
y.grad

/var/folders/rn/zhfgrwvx4r94zbnzqwt6j76h0000gn/T/ipykernel_14100/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:485.)
  y.grad


In [44]:
import numpy as np
states = np.arange(20, dtype=np.float32).reshape(4,5)

In [45]:
actions = np.arange(4).reshape(4,1) + 1

In [46]:
actions

array([[1],
       [2],
       [3],
       [4]])

In [47]:
states_t = torch.tensor(states, requires_grad=True)
states_t

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]], requires_grad=True)

In [37]:
actions_t = torch.tensor(actions)

In [38]:
actions_taken = states_t.gather(1, actions_t)
actions_taken

tensor([[ 0.],
        [ 6.],
        [12.],
        [18.]], grad_fn=<GatherBackward0>)

In [40]:
op = actions_taken **2
op

tensor([[  0.],
        [ 36.],
        [144.],
        [324.]], grad_fn=<PowBackward0>)

In [42]:
op.backward(actions_taken)

In [43]:
states_t.grad

tensor([[  0.,   0.,   0.,   0.,   0.],
        [  0.,  72.,   0.,   0.,   0.],
        [  0.,   0., 288.,   0.,   0.],
        [  0.,   0.,   0., 648.,   0.]])