In [6]:
import numpy as np

w = np.arange(8).reshape((4, 2))
w.shape

(4, 2)

In [7]:
w

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
b = np.arange(2)
b

array([0, 1])

In [9]:
w + b

array([[0, 2],
       [2, 4],
       [4, 6],
       [6, 8]])

In [20]:
a = np.arange(4).reshape(4, 1)
a

array([[0],
       [1],
       [2],
       [3]])

In [22]:
wa = np.multiply(w, a)
wa

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21]])

In [23]:
wa.sum(axis=0)

array([28, 34])

In [26]:
al = wa.sum(axis=0) + b
al

array([28, 35])

In [25]:
al

array([28, 35])

In [34]:
relu = np.maximum(0, al)
relu

array([28, 35])

In [11]:
import torch
x = torch.tensor(3.0, requires_grad=True)
y = 3 * x ** 2
y

tensor(27., grad_fn=<MulBackward0>)

In [10]:
y.backward()
x.grad

tensor(18.)

In [3]:
x.data

tensor(3.)

In [17]:
y.grad_fn

In [12]:
z = 4 * y **3
z

tensor(78732., grad_fn=<MulBackward0>)

In [13]:
z.backward()

In [14]:
y.grad

/var/folders/rn/zhfgrwvx4r94zbnzqwt6j76h0000gn/T/ipykernel_14100/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:485.)
  y.grad


In [44]:
import numpy as np
states = np.arange(20, dtype=np.float32).reshape(4,5)

In [45]:
actions = np.arange(4).reshape(4,1) + 1

In [46]:
actions

array([[1],
       [2],
       [3],
       [4]])

In [47]:
states_t = torch.tensor(states, requires_grad=True)
states_t

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]], requires_grad=True)

In [37]:
actions_t = torch.tensor(actions)

In [38]:
actions_taken = states_t.gather(1, actions_t)
actions_taken

tensor([[ 0.],
        [ 6.],
        [12.],
        [18.]], grad_fn=<GatherBackward0>)

In [40]:
op = actions_taken **2
op

tensor([[  0.],
        [ 36.],
        [144.],
        [324.]], grad_fn=<PowBackward0>)

In [42]:
op.backward(actions_taken)

In [43]:
states_t.grad

tensor([[  0.,   0.,   0.,   0.,   0.],
        [  0.,  72.,   0.,   0.,   0.],
        [  0.,   0., 288.,   0.,   0.],
        [  0.,   0.,   0., 648.,   0.]])

In [2]:

net.layers[0].weights[0, 0]



array([[-0.06663611, -0.02188024,  0.05863566,  0.07545803, -0.16402419,
        -0.07074134, -0.06466604],
       [ 0.04471349, -0.08278085, -0.05594069, -0.0153072 , -0.01844086,
        -0.00296326, -0.04318753],
       [ 0.13512022, -0.10405465,  0.02528395,  0.07332603, -0.04268725,
        -0.0137929 , -0.10638738],
       [ 0.03541213,  0.11231263,  0.04135794,  0.12396837, -0.06632223,
         0.09482266,  0.00282318],
       [-0.0127586 ,  0.052607  , -0.04361942, -0.04765574, -0.00863372,
        -0.02964348,  0.00060703],
       [-0.16201552, -0.05046922, -0.01770124, -0.03389127,  0.01740537,
         0.02722019, -0.02430301],
       [-0.02194014,  0.02008729,  0.03144495, -0.11753134,  0.09384697,
         0.09208753, -0.13759889]])

# Gradient Descent, saving gradients, calculating mean

In [2]:
import numpy as np
from dql_model import Network
net = Network()
input = np.random.randn(4, 75, 75)
net.zero_grad(10)
output = net(input)
output

array([[0.5806745 , 0.60142021, 0.58704945, 0.56904885, 0.60517681,
        0.54258573, 0.61743712, 0.61720335, 0.59521046]])

In [2]:
net.backward(output, 10)

fc2--->, W.shape: (512, 9), DY.shape: (1, 9), Inputs: (1, 512)
	DW.shape: (9, 512), Grads.shape: (10, 512, 9)
fc1--->, W.shape: (1600, 512), DY.shape: (1, 512), Inputs: (1, 1600)
	DW.shape: (512, 1600), Grads.shape: (10, 1600, 512)
conv3--->, W.shape: (64, 64, 3, 3), DY.shape: (64, 5, 5), Inputs: (64, 7, 7)
	DW.shape: (64, 64, 3, 3), Grads.shape: (10, 64, 64, 3, 3)
conv2--->, W.shape: (64, 32, 5, 5), DY.shape: (64, 7, 7), Inputs: (32, 18, 18)
	DW.shape: (64, 32, 5, 5), Grads.shape: (10, 64, 32, 5, 5)
conv1--->, W.shape: (32, 4, 7, 7), DY.shape: (32, 18, 18), Inputs: (4, 75, 75)
	DW.shape: (32, 4, 7, 7), Grads.shape: (10, 32, 4, 7, 7)


In [3]:
# zero_grad

net.layers[-1].zero_grad(10)


if net.layers[-1].inputs.shape[0] == output.shape[0]:
    output = output.T
dw = output.dot(net.layers[-1].inputs)

for e in range(10):
    net.layers[-1].weight_gradients[e] = dw.T


In [6]:
# hacer la media de todos los gradientes
net.layers[-1].weight_gradients.mean(axis=0).shape

(512, 9)

In [10]:
dl = net.layers[-1].backward(output, 0)
dl.shape

fc2--->, W.shape: (512, 9), DY.shape: (1, 9), Inputs: (1, 512)
	DW.shape: (9, 512), Grads.shape: (10, 512, 9)


(1, 512)

In [11]:
dl2 = net.layers[-2].backward(dl, 0)
dl2.shape

fc1--->, W.shape: (1600, 512), DY.shape: (1, 512), Inputs: (1, 1600)
	DW.shape: (512, 1600), Grads.shape: (10, 1600, 512)


(1, 1600)

In [13]:
dl3 = net.layers[-3].backward(dl2, 0)
dl3.shape

(64, 5, 5)

In [16]:
dl4 = net.layers[-4].backward(dl3, 0)
dl4.shape

conv3--->, W.shape: (64, 64, 3, 3), DY.shape: (64, 5, 5), Inputs: (64, 7, 7)
	DW.shape: (64, 64, 3, 3), Grads.shape: (10, 64, 64, 3, 3)


(64, 7, 7)

In [17]:
dl5 = net.layers[-5].backward(dl4, 0)
dl5.shape

conv2--->, W.shape: (64, 32, 5, 5), DY.shape: (64, 7, 7), Inputs: (32, 18, 18)
	DW.shape: (64, 32, 5, 5), Grads.shape: (10, 64, 32, 5, 5)


(32, 18, 18)

In [19]:
dl6 = net.layers[-6].backward(dl5, 0)
dl6.shape

conv1--->, W.shape: (32, 4, 7, 7), DY.shape: (32, 18, 18), Inputs: (4, 75, 75)
	DW.shape: (32, 4, 7, 7), Grads.shape: (10, 32, 4, 7, 7)


(4, 75, 75)

In [9]:
import numpy as np
from dql_model import Network
net = Network()
input = np.random.randn(4, 75, 75)
net.zero_grad(10)
output = net(input)
output

array([[0.65809944, 0.62799003, 0.63571133, 0.67175606, 0.62760426,
        0.66568968, 0.64389497, 0.61460225, 0.6604779 ]])

In [10]:
d_loss = np.zeros_like(output)
d_loss[0, 5] = 0.2
d_loss


array([[0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. ]])

In [27]:
d = net.layers[-1].backward(d_loss, 0)
d = net.layers[-2].backward(d, 0)
d = net.layers[-3].backward(d, 0)
d = net.layers[-4].backward(d, 0)
d = net.layers[-5].backward(d, 0)



(10, 1600, 512)

In [17]:
net.backward(output, 0)

In [4]:
for n in range(10):
    dl = np.random.normal(0, 1, (output.shape))
    net.backward(dl, n)

fc2--->, W.shape: (512, 9), DY.shape: (1, 9), Inputs: (1, 512)
	DW.shape: (9, 512), Grads.shape: (10, 512, 9)
fc1--->, W.shape: (1600, 512), DY.shape: (1, 512), Inputs: (1, 1600)
	DW.shape: (512, 1600), Grads.shape: (10, 1600, 512)
conv3--->, W.shape: (64, 64, 3, 3), DY.shape: (64, 5, 5), Inputs: (64, 7, 7)
	DW.shape: (64, 64, 3, 3), Grads.shape: (10, 64, 64, 3, 3)
conv2--->, W.shape: (64, 32, 5, 5), DY.shape: (64, 7, 7), Inputs: (32, 18, 18)
	DW.shape: (64, 32, 5, 5), Grads.shape: (10, 64, 32, 5, 5)
conv1--->, W.shape: (32, 4, 7, 7), DY.shape: (32, 18, 18), Inputs: (4, 75, 75)
	DW.shape: (32, 4, 7, 7), Grads.shape: (10, 32, 4, 7, 7)
fc2--->, W.shape: (512, 9), DY.shape: (1, 9), Inputs: (1, 512)
	DW.shape: (9, 512), Grads.shape: (10, 512, 9)
fc1--->, W.shape: (1600, 512), DY.shape: (1, 512), Inputs: (1, 1600)
	DW.shape: (512, 1600), Grads.shape: (10, 1600, 512)
conv3--->, W.shape: (64, 64, 3, 3), DY.shape: (64, 5, 5), Inputs: (64, 7, 7)
	DW.shape: (64, 64, 3, 3), Grads.shape: (10, 64, 

In [5]:
net.layers[-6].bias_gradients.mean(axis=0).shape

(32, 1)

In [6]:
net.layers[-6].weights[0,0,0]

array([-0.03010941,  0.02391884, -0.06601707, -0.04852788, -0.05987286,
       -0.11834934, -0.0203637 ])

In [7]:
from optim import SGD

optim = SGD(net, 0.1)
optim.step()

In [8]:
net.layers[-6].weights[0,0,0]

array([-0.03004637,  0.02401608, -0.06602209, -0.04821476, -0.06029992,
       -0.11782329, -0.02075715])

In [31]:
import layers
if not (isinstance(net.layers[-6], layers.Flatten) or isinstance(net.layers[-6], layers.ReLU)):
    print(True)

True


In [44]:
info = {"game_number": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38], "frames": [1213, 2940, 4343, 4947, 5388, 6467, 7034, 7953, 8446, 9621, 10092, 10158, 10357, 10503, 10743, 11082, 11139, 11595, 11836, 12321, 12465, 12551, 12933, 13108, 13533, 13652, 13868, 14069, 14314, 14405, 14510, 14813, 14960, 15290, 15356, 15426, 15621, 15680], "epsilon": [0.9959566666666667, 0.9902, 0.9855233333333333, 0.98351, 0.98204, 0.9784433333333333, 0.9765533333333334, 0.97349, 0.9718466666666666, 0.96793, 0.96636, 0.96614, 0.9654766666666666, 0.96499, 0.96419, 0.96306, 0.96287, 0.96135, 0.9605466666666667, 0.95893, 0.95845, 0.9581633333333334, 0.95689, 0.9563066666666666, 0.95489, 0.9544933333333333, 0.9537733333333334, 0.9531033333333333, 0.9522866666666666, 0.9519833333333333, 0.9516333333333333, 0.9506233333333334, 0.9501333333333334, 0.9490333333333333, 0.9488133333333333, 0.94858, 0.94793, 0.9477333333333333], "score": [150, 150, 270, 40, 210, -10, 100, 180, -30, 80, 180, -150, 180, -150, -80, 140, -100, 210, 200, 120, 160, 150, 150, 200, 200, 60, 160, 190, 110, 50, 100, 140, 150, -50, 150, 150, -140, 150], "mean_score": [150.0, 150.0, 190.0, 152.5, 164.0, 135.0, 130.0, 136.25, 117.77777777777777, 114.0, 120.0, 97.5, 103.84615384615384, 85.71428571428571, 74.66666666666667, 78.75, 68.23529411764706, 76.11111111111111, 82.63157894736842, 84.5, 88.0952380952381, 90.9090909090909, 93.47826086956522, 97.91666666666667, 102.0, 100.38461538461539, 102.5925925925926, 105.71428571428571, 105.86206896551724, 104.0, 103.87096774193549, 105.0, 106.36363636363636, 101.76470588235294, 103.14285714285714, 104.44444444444444, 97.83783783783784, 99.21052631578948], "best_mean_score": [150.0, 150.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0, 190.0], "cost": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6.923309948288295, 5.267710164850083, 6.479084967093, 9.449160717845523, 6.034179519867944, 9.59020923611482, 11.200093254559794, 10.217722684106217, 11.085057879716679, 14.714819990195634, 21.606539702981063, 27.9415141637273, 34.47913301751461, 56.26761204888064, 98.89904267349951, 172.53925437436152, 254.98713133832982, 397.74531306078035, 662.4492091667508, 930.0165655225267, 1129.4068367703328, 1823.5670659907328, 2989.510555234375, 5238.882234524625, 7656.15802511248, 9229.029905792651, 12327.235649655468, 16187.964528543185]}
import pandas as pd
import plotly.express as px
px.line(info, x='frames', y='cost', title='Cost')

