In [6]:
import numpy as np

w = np.arange(8).reshape((4, 2))
w.shape

(4, 2)

In [7]:
w

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
b = np.arange(2)
b

array([0, 1])

In [9]:
w + b

array([[0, 2],
       [2, 4],
       [4, 6],
       [6, 8]])

In [20]:
a = np.arange(4).reshape(4, 1)
a

array([[0],
       [1],
       [2],
       [3]])

In [22]:
wa = np.multiply(w, a)
wa

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21]])

In [23]:
wa.sum(axis=0)

array([28, 34])

In [26]:
al = wa.sum(axis=0) + b
al

array([28, 35])

In [25]:
al

array([28, 35])

In [34]:
relu = np.maximum(0, al)
relu

array([28, 35])

In [11]:
import torch
x = torch.tensor(3.0, requires_grad=True)
y = 3 * x ** 2
y

tensor(27., grad_fn=<MulBackward0>)

In [10]:
y.backward()
x.grad

tensor(18.)

In [3]:
x.data

tensor(3.)

In [17]:
y.grad_fn

In [12]:
z = 4 * y **3
z

tensor(78732., grad_fn=<MulBackward0>)

In [13]:
z.backward()

In [14]:
y.grad

/var/folders/rn/zhfgrwvx4r94zbnzqwt6j76h0000gn/T/ipykernel_14100/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:485.)
  y.grad


In [44]:
import numpy as np
states = np.arange(20, dtype=np.float32).reshape(4,5)

In [45]:
actions = np.arange(4).reshape(4,1) + 1

In [46]:
actions

array([[1],
       [2],
       [3],
       [4]])

In [47]:
states_t = torch.tensor(states, requires_grad=True)
states_t

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]], requires_grad=True)

In [37]:
actions_t = torch.tensor(actions)

In [38]:
actions_taken = states_t.gather(1, actions_t)
actions_taken

tensor([[ 0.],
        [ 6.],
        [12.],
        [18.]], grad_fn=<GatherBackward0>)

In [40]:
op = actions_taken **2
op

tensor([[  0.],
        [ 36.],
        [144.],
        [324.]], grad_fn=<PowBackward0>)

In [42]:
op.backward(actions_taken)

In [43]:
states_t.grad

tensor([[  0.,   0.,   0.,   0.,   0.],
        [  0.,  72.,   0.,   0.,   0.],
        [  0.,   0., 288.,   0.,   0.],
        [  0.,   0.,   0., 648.,   0.]])

In [2]:

net.layers[0].weights[0, 0]



array([[-0.06663611, -0.02188024,  0.05863566,  0.07545803, -0.16402419,
        -0.07074134, -0.06466604],
       [ 0.04471349, -0.08278085, -0.05594069, -0.0153072 , -0.01844086,
        -0.00296326, -0.04318753],
       [ 0.13512022, -0.10405465,  0.02528395,  0.07332603, -0.04268725,
        -0.0137929 , -0.10638738],
       [ 0.03541213,  0.11231263,  0.04135794,  0.12396837, -0.06632223,
         0.09482266,  0.00282318],
       [-0.0127586 ,  0.052607  , -0.04361942, -0.04765574, -0.00863372,
        -0.02964348,  0.00060703],
       [-0.16201552, -0.05046922, -0.01770124, -0.03389127,  0.01740537,
         0.02722019, -0.02430301],
       [-0.02194014,  0.02008729,  0.03144495, -0.11753134,  0.09384697,
         0.09208753, -0.13759889]])

# Gradient Descent, saving gradients, calculating mean

In [1]:
import numpy as np
from dql_model import Network
net = Network()
input = np.random.randn(4, 75, 75)
net.zero_grad(10)
output = net(input)
output

array([[0.64846756, 0.66892058, 0.65991511, 0.65238567, 0.62497674,
        0.65529381, 0.63013929, 0.62044188, 0.63148644]])

In [2]:
net.backward(output, 10)

fc2--->, W.shape: (512, 9), DY.shape: (1, 9), Inputs: (1, 512)
	DW.shape: (9, 512), Grads.shape: (10, 512, 9)
fc1--->, W.shape: (1600, 512), DY.shape: (1, 512), Inputs: (1, 1600)
	DW.shape: (512, 1600), Grads.shape: (10, 1600, 512)
conv3--->, W.shape: (64, 64, 3, 3), DY.shape: (64, 5, 5), Inputs: (64, 7, 7)
	DW.shape: (64, 64, 3, 3), Grads.shape: (10, 64, 64, 3, 3)
conv2--->, W.shape: (64, 32, 5, 5), DY.shape: (64, 7, 7), Inputs: (32, 18, 18)
	DW.shape: (64, 32, 5, 5), Grads.shape: (10, 64, 32, 5, 5)
conv1--->, W.shape: (32, 4, 7, 7), DY.shape: (32, 18, 18), Inputs: (4, 75, 75)
	DW.shape: (32, 4, 7, 7), Grads.shape: (10, 32, 4, 7, 7)


In [3]:
# zero_grad

net.layers[-1].zero_grad(10)


if net.layers[-1].inputs.shape[0] == output.shape[0]:
    output = output.T
dw = output.dot(net.layers[-1].inputs)

for e in range(10):
    net.layers[-1].weight_gradients[e] = dw.T


In [6]:
# hacer la media de todos los gradientes
net.layers[-1].weight_gradients.mean(axis=0).shape

(512, 9)

In [17]:
shape = list(net.layers[-1].weights.shape)

In [18]:
shape

[512, 9]

In [19]:
shape.insert(0, 10)

In [20]:
shape

[10, 512, 9]

In [22]:
np.zeros(shape).shape

(10, 512, 9)